In [1]:
import numpy as np

In [14]:
#1
#(1)
one = np.random.randint(10,31,(2,5))
print(one)
#(2)
two = np.random.randn(3,3,1)
print(two)
#(3)
three = np.random.rand(6)
print(three)
#(4)
four = np.diag(np.arange(1,4.5,0.5))
print(four)

[[26 29 14 25 28]
 [26 20 15 28 11]]
[[[ 0.39009502]
  [-1.19450646]
  [ 0.76144943]]

 [[-1.5027885 ]
  [-1.05234584]
  [ 1.73042922]]

 [[-0.85569705]
  [-0.26952816]
  [-0.96489147]]]
[0.09913467 0.16196042 0.72187477 0.40220962 0.00323071 0.38186983]
[[1.  0.  0.  0.  0.  0.  0. ]
 [0.  1.5 0.  0.  0.  0.  0. ]
 [0.  0.  2.  0.  0.  0.  0. ]
 [0.  0.  0.  2.5 0.  0.  0. ]
 [0.  0.  0.  0.  3.  0.  0. ]
 [0.  0.  0.  0.  0.  3.5 0. ]
 [0.  0.  0.  0.  0.  0.  4. ]]


In [20]:
#2
Z = np.zeros((8,8), dtype=np.int64)
#(1)
Z[1::2,0::2] = 1
print(Z)
#(2)
Z[::2,1::2] = 1
print(Z)

[[0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]]
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [31]:
#3
TH = np.array([np.arange(6)]*6) + np.arange(0, 51, 10).reshape(6, 1)
print(TH)
#(1)
print(TH[0,3:5])
#(2)
print(TH[4:,4:])
#(3)
print(TH[:,2])
#(4)
print(TH[:,2:3])
#(5)
TH[:,2] = np.arange(6)
print(TH)
#(6)
print(TH[2::2,::2])
#(7)
TH[2::2,::2] = np.arange(1,7).reshape(2,3)
print(TH)

[[ 0  1  2  3  4  5]
 [10 11 12 13 14 15]
 [20 21 22 23 24 25]
 [30 31 32 33 34 35]
 [40 41 42 43 44 45]
 [50 51 52 53 54 55]]
[3 4]
[[44 45]
 [54 55]]
[ 2 12 22 32 42 52]
[[ 2]
 [12]
 [22]
 [32]
 [42]
 [52]]
[[ 0  1  0  3  4  5]
 [10 11  1 13 14 15]
 [20 21  2 23 24 25]
 [30 31  3 33 34 35]
 [40 41  4 43 44 45]
 [50 51  5 53 54 55]]
[[20  2 24]
 [40  4 44]]
[[ 0  1  0  3  4  5]
 [10 11  1 13 14 15]
 [ 1 21  2 23  3 25]
 [30 31  3 33 34 35]
 [ 4 41  5 43  6 45]
 [50 51  5 53 54 55]]


In [32]:
#4
Z = np.random.rand(5)
Zmax, Zmin = Z.max(), Z.min()
Z = (Z - Zmin)/(Zmax - Zmin)
print(Z)

[0.         0.85356027 0.74198909 0.46266276 1.        ]


In [35]:
#5
Z = np.random.uniform(0,10,10)
print(Z)
print(Z - Z%1)
print(np.floor(Z))
print(np.ceil(Z)-1)

[5.3784674  4.60932127 6.52017058 3.60018874 6.34793795 2.5407615
 8.33548444 8.68113047 1.1500958  7.65630693]
[5. 4. 6. 3. 6. 2. 8. 8. 1. 7.]
[5. 4. 6. 3. 6. 2. 8. 8. 1. 7.]
[5. 4. 6. 3. 6. 2. 8. 8. 1. 7.]


In [37]:
#6
NP = np.arange(100)
NP[NP%2==0] = -1*NP[NP%2==0]
print(NP)

[  0   1  -2   3  -4   5  -6   7  -8   9 -10  11 -12  13 -14  15 -16  17
 -18  19 -20  21 -22  23 -24  25 -26  27 -28  29 -30  31 -32  33 -34  35
 -36  37 -38  39 -40  41 -42  43 -44  45 -46  47 -48  49 -50  51 -52  53
 -54  55 -56  57 -58  59 -60  61 -62  63 -64  65 -66  67 -68  69 -70  71
 -72  73 -74  75 -76  77 -78  79 -80  81 -82  83 -84  85 -86  87 -88  89
 -90  91 -92  93 -94  95 -96  97 -98  99]


In [38]:
#7
Celsius = np.arange(20,31)
Fahrenheit = 9*Celsius/5+32
print(Fahrenheit)

[68.  69.8 71.6 73.4 75.2 77.  78.8 80.6 82.4 84.2 86. ]


In [42]:
np.random.seed(123)
mat = np.random.randn(6, 4)
print(mat)
#8
mat = np.hstack([mat, np.exp(mat[:,0])[:,np.newaxis]])
print(mat)

[[-1.0856306   0.99734545  0.2829785  -1.50629471]
 [-0.57860025  1.65143654 -2.42667924 -0.42891263]
 [ 1.26593626 -0.8667404  -0.67888615 -0.09470897]
 [ 1.49138963 -0.638902   -0.44398196 -0.43435128]
 [ 2.20593008  2.18678609  1.0040539   0.3861864 ]
 [ 0.73736858  1.49073203 -0.93583387  1.17582904]]
[[-1.0856306   0.99734545  0.2829785  -1.50629471  0.33768877]
 [-0.57860025  1.65143654 -2.42667924 -0.42891263  0.56068263]
 [ 1.26593626 -0.8667404  -0.67888615 -0.09470897  3.54641154]
 [ 1.49138963 -0.638902   -0.44398196 -0.43435128  4.44326571]
 [ 2.20593008  2.18678609  1.0040539   0.3861864   9.07869158]
 [ 0.73736858  1.49073203 -0.93583387  1.17582904  2.09042747]]


In [43]:
#9
mat[:,::2] += 1
mat[:,1::2] += -1
mat
#or mat = mat+np.array([1,-1,1,-1,1])

[[-8.56306033e-02 -2.65455342e-03  1.28297850e+00 -2.50629471e+00
   1.33768877e+00]
 [ 4.21399748e-01  6.51436537e-01 -1.42667924e+00 -1.42891263e+00
   1.56068263e+00]
 [ 2.26593626e+00 -1.86674040e+00  3.21113848e-01 -1.09470897e+00
   4.54641154e+00]
 [ 2.49138963e+00 -1.63890200e+00  5.56018040e-01 -1.43435128e+00
   5.44326571e+00]
 [ 3.20593008e+00  1.18678609e+00  2.00405390e+00 -6.13813601e-01
   1.00786916e+01]
 [ 1.73736858e+00  4.90732028e-01  6.41661316e-02  1.75829045e-01
   3.09042747e+00]]


In [44]:
#10
mat*np.array([1/10,1/10,1/10,10,10,10]).reshape(6,1)
mat

array([[-8.56306033e-02, -2.65455342e-03,  1.28297850e+00,
        -2.50629471e+00,  1.33768877e+00],
       [ 4.21399748e-01,  6.51436537e-01, -1.42667924e+00,
        -1.42891263e+00,  1.56068263e+00],
       [ 2.26593626e+00, -1.86674040e+00,  3.21113848e-01,
        -1.09470897e+00,  4.54641154e+00],
       [ 2.49138963e+00, -1.63890200e+00,  5.56018040e-01,
        -1.43435128e+00,  5.44326571e+00],
       [ 3.20593008e+00,  1.18678609e+00,  2.00405390e+00,
        -6.13813601e-01,  1.00786916e+01],
       [ 1.73736858e+00,  4.90732028e-01,  6.41661316e-02,
         1.75829045e-01,  3.09042747e+00]])

In [49]:
#11
print(np.median( mat , axis=0))
print(np.percentile( mat , q=70, axis=0))

[ 2.00165242  0.24403874  0.43856594 -1.2618108   3.81841951]
[ 2.37866294  0.57108428  0.91949827 -0.85426128  4.99483862]


In [52]:
#12
print(np.sort(mat[:,2])[::-1])

[ 2.0040539   1.2829785   0.55601804  0.32111385  0.06416613 -1.42667924]


In [54]:
#13
print(np.sum(np.exp(mat)>3, axis=1))

[2 1 2 2 4 2]


In [56]:
#14
np.nonzero(mat > np.mean(mat, axis=0))

(array([0, 0, 1, 2, 2, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5]),
 array([1, 2, 1, 3, 4, 0, 2, 4, 0, 1, 2, 4, 0, 1, 3]))

In [58]:
np.random.seed(123)
M = np.random.randint(1, 50, size=(3,3))
print(M)
#15
np.dot(M,np.transpose(M))

[[46  3 29]
 [35 39 18]
 [20 43 23]]


array([[2966, 2249, 1716],
       [2249, 3070, 2791],
       [1716, 2791, 2778]])

In [60]:
#16
np.linalg.det(M)

25347.999999999975

In [61]:
#17
np.linalg.inv(M)

array([[ 0.00485245,  0.04647309, -0.04248856],
       [-0.01755563,  0.0188575 ,  0.00737731],
       [ 0.02860186, -0.07566672,  0.06663248]])