In [1]:
import numpy as np

#1
np.random.seed(123)
aMat = np.random.randint(0, 100, (6, 10))
#(1)
aVec = np.where(np.mean(aMat, axis=0) > 50, 1, 0)
print(aVec)
#(2)
print(aMat[(aMat[:,4] > 50) | (aMat[:,6] < 30) , :])
#(3)
aMat[[3,1],[1,6]] = 999
print(aMat)
#(4)
print(np.mean(aMat[~np.any( aMat==999, axis=1),:],axis=0))
print(np.std(aMat[~np.any(aMat==999,axis=1),:],axis=0))
#(5)
print
aMat[aMat == 999] = np.mean(aMat, axis=0)[np.nonzero(aMat==999)[1]]
print(aMat)
#(6)
aMat2 = np.hstack([aMat, np.sum(aMat, axis=1).reshape(6,1)])
aMat2 = np.vstack([aMat2, np.sum(aMat2, axis=0)])
print(aMat2)

[1 1 1 1 0 1 1 1 1 0]
[[66 92 98 17 83 57 86 97 96 47]
 [61 48  7 99 92 52 97 85 94 27]]
[[ 66  92  98  17  83  57  86  97  96  47]
 [ 73  32  46  96  25  83 999  36  96  80]
 [ 68  49  55  67   2  84  39  66  84  47]
 [ 61 999   7  99  92  52  97  85  94  27]
 [ 34  97  76  40   3  69  64  75  34  58]
 [ 10  22  77  18  15  27  30  52  70  26]]
[44.5  65.   76.5  35.5  25.75 59.25 54.75 72.5  71.   44.5 ]
[24.05722345 31.05640031 15.20690633 20.37768387 33.44678609 20.93292861
 21.92458666 16.34778272 23.2594067  11.58663023]
[[ 66  92  98  17  83  57  86  97  96  47]
 [ 73  32  46  96  25  83 219  36  96  80]
 [ 68  49  55  67   2  84  39  66  84  47]
 [ 61 215   7  99  92  52  97  85  94  27]
 [ 34  97  76  40   3  69  64  75  34  58]
 [ 10  22  77  18  15  27  30  52  70  26]]
[[  66   92   98   17   83   57   86   97   96   47  739]
 [  73   32   46   96   25   83  219   36   96   80  786]
 [  68   49   55   67    2   84   39   66   84   47  561]
 [  61  215    7   99   92   52   

In [2]:
#2
np.random.seed(123)
MAT = np.random.exponential(scale=1/5, size=(10, 7))
MAT= np.around( MAT, decimals=3 )
print(MAT)
#(1)
m= np.median(MAT)
Q1=np.percentile(MAT, q=25)
Q3=np.percentile(MAT, q=75)
print(MAT[(MAT<( Q1-1.5*(Q3-Q1))) | (MAT>( Q3+1.5*(Q3-Q1)))])
#(2)
mdiff = np.abs(MAT - m )
print(MAT[ mdiff== np.min(mdiff) ])
print(np.nonzero( mdiff== np.min(mdiff)))
#(3)
print(MAT[np.argsort(MAT[:,1])])
#(4)
print(MAT[np.argsort(np.mean(MAT,axis=0))[::-1]])
#(5)
print(MAT[[[0],[2]],[1,3,4]])
print(MAT[[0,0,0,2,2,2],[1,3,4,1,3,4]])
#(6)
MAT[(MAT<( Q1-1.5*(Q3-Q1))) | (MAT>( Q3+1.5*(Q3-Q1)))] = np.nan
print(MAT)
#(7)
print(MAT[np.sum( np.isnan(MAT), axis=1 ) > 0, : ])

[[0.238 0.067 0.051 0.16  0.254 0.11  0.79 ]
 [0.231 0.131 0.1   0.084 0.261 0.115 0.012]
 [0.102 0.268 0.04  0.039 0.152 0.152 0.201]
 [0.379 0.258 0.189 0.256 0.078 0.09  0.052]
 [0.07  0.199 0.019 0.114 0.113 0.136 0.111]
 [0.075 0.111 0.448 0.577 0.139 0.196 0.025]
 [0.076 0.107 0.402 0.058 0.132 0.848 0.147]
 [0.19  0.026 0.35  0.185 0.158 0.084 0.073]
 [0.108 0.229 0.417 0.143 0.221 0.176 0.196]
 [0.225 0.369 0.017 0.289 0.056 0.043 0.17 ]]
[0.79  0.577 0.848]
[0.143]
(array([8]), array([3]))
[[0.19  0.026 0.35  0.185 0.158 0.084 0.073]
 [0.238 0.067 0.051 0.16  0.254 0.11  0.79 ]
 [0.076 0.107 0.402 0.058 0.132 0.848 0.147]
 [0.075 0.111 0.448 0.577 0.139 0.196 0.025]
 [0.231 0.131 0.1   0.084 0.261 0.115 0.012]
 [0.07  0.199 0.019 0.114 0.113 0.136 0.111]
 [0.108 0.229 0.417 0.143 0.221 0.176 0.196]
 [0.379 0.258 0.189 0.256 0.078 0.09  0.052]
 [0.102 0.268 0.04  0.039 0.152 0.152 0.201]
 [0.225 0.369 0.017 0.289 0.056 0.043 0.17 ]]
[[0.102 0.268 0.04  0.039 0.152 0.152 0.201]
